infra: initial backend manifest
KonomiAI/Chronicle pull request #194
Opened 2022-04-25 04:17 UTC by NguyenPatrick

### Related Issue(s)
resolves #187

### Dependencies
depends on https://github.com/KonomiAI/Chronicle/pull/193

### Quick overview of the change
- Backend manifest for Chronicle API with external secrets
- TODO: dynamically push changes to k8s cluster with GH actions

2022-04-25 14:45 UTC, callmekungfu approved these changes

2022-04-25 16:32 UTC, andrewpratheepan requested changes
Minor requests for update

2022-04-25 16:32 UTC, andrewpratheepan commented on infrastructure/kubernetes/chronicle-backend.yaml
> +                  name: chronicle-staging-mongodb-url-secret
add [resource requests ](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/)to the manifest as well

2022-04-26 02:58 UTC, NguyenPatrick commented on infrastructure/kubernetes/chronicle-backend.yaml
> +                  name: chronicle-staging-mongodb-url-secret
Sandbox namespace was typo, will change to `staging` I'm assuming you're referring to a directory called `infrastruture/kubernetes/staging`? We can also put the manifests for the staging secrets there as well

2022-06-01 16:19 UTC, merged