feat: dynamic data in custom fields
KonomiAI/Chronicle pull request #241
Opened 2022-09-27 16:09 UTC by callmekungfu

### Related Issue(s)

resolves #240 

### Quick overview of the change

- Added the ability to create dynamic data questions
- Added the ability to respond and render dynamic data questions
- Added basic documentations for custom forms

### Quick testing guide

2022-09-28 01:04 UTC, Wuon requested changes

2022-09-28 01:04 UTC, Wuon commented on client/src/components/form-viewer/form-fields-factory.tsx
> +        help
missing period in this alert

2022-09-28 01:04 UTC, Wuon commented on server/src/models/forms/form.controller.ts
> +    console.log(validateWithLatest);
wee woo console.log alert found

2022-09-28 01:04 UTC, Wuon commented on server/src/models/forms/form.controller.ts
> +      console.log(validateWithLatest.errors);
here too

2022-09-30 17:59 UTC, callmekungfu commented on client/src/components/form-builder/components/StaticMultipleChoiceBuilder.tsx
> +    name: `${context}sections.${sectionIndex}.fields.${index}.options`,
You mean make the name generation a function? I do that if the name gets used repeatedly, in this case it doesn't so we keep it inline

2022-09-30 17:59 UTC, callmekungfu commented on client/src/components/form-builder/form-field.tsx
> +  const isDynamicOptionQuestionType = type === 'dataSourceSelect';
Good point, let me see if I can enumerate them in c-form and pass that around

2022-09-30 18:44 UTC, Wuon commented on client/src/components/form-builder/components/StaticMultipleChoiceBuilder.tsx
> +    name: `${context}sections.${sectionIndex}.fields.${index}.options`,
why is everything else `.` notation except for first part?

eg:
`${context}sections` vs `${context}.sections`

2022-09-30 19:31 UTC, Wuon approved these changes

2022-10-01 01:11 UTC, merged